config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'
  post 'ping_home/:id', to: 'home#ping_to_home', as: :user_ping_to_home
  post 'ping_about/:id', to: 'home#ping_to_about', as: :user_ping_to_about

  devise_for :users

  devise_scope :user do
    authenticated :user do
			root to: "home#index"	
	  end
		root to: "devise/sessions#new"
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
	belongs_to :recipient, class_name: "User"
	belongs_to :notifiable, polymorphic: true

	after_commit -> { NotificationRelayJob.perform_later(self) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :own_notifications, class_name: "Notification", foreign_key: "user_id", dependent: :destroy
  has_many :notifications, foreign_key: :recipient_id, dependent: :destroy

  scope :all_without, ->(user) { (where.not(id: user.id)) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@users = User.all_without(current_user)
  end

  def ping_to_home
    notification = current_user.own_notifications.create(
  		recipient_id: params[:id],
      title: "#{current_user.email} ping you on home",
      description: "email: #{current_user.email}, action: #{ action_name }",
  		url: home_index_url,
      action: action_name,
  		notifiable: current_user
  	)
  	redirect_back(fallback_location: root_path)
  end

  def ping_to_about
    notification = current_user.own_notifications.create(
      recipient_id: params[:id],
      title: "#{current_user.email} ping you on about",
      description: "email: #{current_user.email}, action: #{ action_name }",
      url: home_about_url,
      action: action_name,
      notifiable: current_user
    )
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/index.html.erb
<ul class="list-group" style="width: 50%;">
	<% @users.each do |user| %>
	  <li class="list-group-item justify-content-between">
	  	<%= user.email %>
	  	<span class="row">
	  		<%= button_to "Ping to home", user_ping_to_home_path(user), class: "btn btn-success", form_class: "col-md-6" %>
	  		<%= button_to "Ping to about", user_ping_to_about_path(user), class: "btn btn-info", form_class: "col-md-6" %>
	  		</span>
	  </li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PushNotification</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if user_signed_in? %>
	  	<nav class="navbar navbar-toggleable-md navbar-light bg-faded navbar-inverse bg-primary">
			  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			    <span class="navbar-toggler-icon"></span>
			  </button>
			  <a class="navbar-brand" href="/	">PushDemo</a>

			  <div class="collapse navbar-collapse" id="navbarSupportedContent">
			    <ul class="navbar-nav mr-auto">
			      <li class="nav-item active">
			        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
			      </li>
			      <li class="nav-item active">
			        <a class="nav-link" href="<%= home_about_path %>">About</a>
			      </li>
			    </ul>
			    <ul class="nav nav-tabs">
					  <li class="nav-item dropdown">
					    <a class="nav-link dropdown-toggle navbar-text" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Welcome, <%= current_user.email %></a>
					    <div class="dropdown-menu">
					    	<%= link_to "Logout", destroy_user_session_path, class: "dropdown-item", method: :delete %>
					    </div>
					  </li>
					</ul>
			  </div>
			</nav>
		<% else %>
			<nav class="navbar navbar-toggleable-md navbar-light bg-faded navbar-inverse bg-primary">
			  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			    <span class="navbar-toggler-icon"></span>
			  </button>
			  <a class="navbar-brand" href="/">PushDemo</a>
			  <div class="collapse navbar-collapse" id="navbarSupportedContent">
			    <ul class="navbar-nav mr-auto">
			      <li class="nav-item active">
			        <a class="nav-link" href="<%= new_user_session_path %>">Login</a>
			      </li>
			      <li class="nav-item active">
			        <a class="nav-link" href="<%= new_user_registration_path %>">Sign Up</a>
			      </li>
			    </ul>
			  </div>
			</nav>
		<% end %>
    <%= yield %>
  </body>
</html>